[package]
name = "tuntap"
version = "0.1.0"
authors = [
    "Vanhala Antti <antti.vanhala@aalto.fi>",
    "Matthew Bentley <matthew@bentley.link"
]
license = "MIT"
build = "build.rs"

[dependencies]
libc = "^0.2"
